"""create tables

Revision ID: 290239710e56
Revises: ffdc0a98111c
Create Date: 2021-02-09 12:44:45.666246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290239710e56'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dreams',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('keywords', sa.String(length=50), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('dreamer_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['dreamer_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('fragments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('emotions', sa.String(
                        length=100), nullable=True),
                    sa.Column('setting', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dreams_fragments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('dream_id', sa.Integer(), nullable=False),
                    sa.Column('fragment_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ),
                    sa.ForeignKeyConstraint(
                        ['fragment_id'], ['fragments.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dreams_fragments')
    op.drop_table('fragments')
    op.drop_table('dreams')
    # ### end Alembic commands ###
